general {
    background = rgba(1a1b26ff)
    base = rgba(24283bff)
    alternate_base = rgba(292e42ff)
    text = rgba(c0caf5ff)
    bright_text = rgba(ff9e64ff)
    accent = rgba(7aa2f7ff)
    accent_secondary = rgba(bb9af7ff)

    font_family = JetBrainsMono Nerd Font Propo
    font_family_monospace = JetBrainsMono Nerd Font Propo

    font_size = 12
    small_font_size = 10
    h1_size = 17
    h2_size = 15
    h3_size = 13

    rounding_large = 12
    rounding_small = 6
}
