cursor #e2e7ea
cursor_text_color #c1c8cc

foreground            #e2e7ea
background            #0b0f12
selection_foreground  #07231d
selection_background  #c6c08f
url_color             #8fd6c6

color0   #12161a
color1   #f69b6e
color2   #6bd671
color3   #fff372
color4   #7acbb9
color5   #266355
color6   #8fd6c6
color7   #d3e0dd
color8   #808b88
color9   #ffbf9f
color10  #a5ffab
color11  #fff7a5
color12  #a9ebdc
color13  #c3fff1
color14  #d8fff6
color15  #f8fffd
